[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
rust-version = "1.96"
license = "GPL-3.0-or-later"

[workspace.dependencies]
lz4_flex = { version = "0.11", default-features = false, features = ["std"] }
png = "0.17"
fontdue = "0.9"
libloading = "0.8"
winit = "0.30"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
gl = "0.14"
cpal = "0.15"
gilrs = "0.11"
tempfile = "3"
unicode-normalization = "0.1"
resvg = { version = "0.48", default-features = false }
usvg = { version = "0.48", default-features = false }
cc = "1.2"

[profile.device]
inherits = "release"
lto = "fat"
codegen-units = 1
